---
output: 
  html_document: 
    highlight: textmate
    theme: paper
---
##Porcentagem de vitórias do União Agrícola Barbarense Futebol Clube entre os anos de 2009 e 2019
##José Henrique Rasteiro Gaspar

[matchendirect]: https://www.matchendirect.fr/equipe/uniao-barbarense.html

**Parte 1 - recolhimento dos dados

```{r DADOS}
anos<-c("2009","2010","2011","2012","2013","2014","2015","2016","2017","2018","2019")

derrotas<-c(9,10,8,9,18,18,11,9,14,10,6)

vitórias<-c(7,10,3,12,4,11,15,9,4,4,3)

empates<-c(3,5,7,6,8,8,9,3,1,5,2)

total_de_jogos<-c(19,25,18,27,30,37,35,22,19,19,11)

campeonato<-c("Série A2","Série A2","Série A2","Série A2",
               "Série A1 + Copa Paulista","Série A2 + Copa Paulista",
               "Série A2 + Copa Paulista","Série A2",
               "Série A2","Série A3","Paulista Série B")

União_Barbarense<-data.frame(anos,derrotas,vitórias,empates,total_de_jogos,campeonato)
```

------

anos|derrotas|vitórias|empates|total_de_jogos|campeonato
----|--------|--------|-------|--------------|----------
2009|    9   |    7   |   3   |       19     |Aérie A2
2010|    10  |    10  |   5   |       25     |Série A2
2011|    8   |    3   |   7   |       18     |Série A2
2012|    9   |    12  |   6   |       27     |Série A2
2013|    18  |    4   |   8   |       30     |Série A1 + Copa Paulista
2014|    18  |    11  |   8   |       37     |Série A2 + Copa Paulista  
2015|    11  |    15  |   9   |       35     |Série A2 + Copa Paulista
2016|    9   |    9   |   3   |       22     |Série A2
2017|    14  |    4   |   1   |       19     |Série A2
2018|    10  |    4   |   5   |       19     |Série A3
2019|    6   |    3   |   2   |       11     |Paulista Série B
    |


------

**Parte 2 - plotar os resultados
```{r PLOTAGEM}
library("ggplot2", lib.loc="C:/Program Files/R/R-3.6.0/library")

ggplot(data=União_Barbarense,aes(x=anos,y=(vitórias/total_de_jogos)))+
  geom_bar(stat="identity",aes(fill=campeonato))+
  ggtitle("Porcentagem de vitórias do União Barbarense FC entre os anos de 2009 e 2019",
             subtitle="Fonte: matchendirect.fr")+
  scale_x_discrete(name="Anos")+
  scale_y_continuous(name="Porcentagem de vitórias",labels=scales::percent)+
  theme(legend.key.size = unit(1,"lines"))
```

**Parte 3 - calculo da média e do desvio padrão

```{r MÉDIA E DESVIO PADRÃO}

median(vitórias/total_de_jogos)*100

sd(vitórias/total_de_jogos)*100

```

**FIM**




